name: Release Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete non-latest releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --limit 1000 --json tagName,isLatest \
            | jq -r '.[] | select(.isLatest == false) | .tagName' \
            | xargs -r -I {} gh release delete {} -y
